parameters:
    ezrepoforms.field_type_form_mapper.registry.class: EzSystems\RepositoryForms\FieldType\FieldTypeFormMapperRegistry
    ezrepoforms.content_type.update.form_type.class: EzSystems\RepositoryForms\Form\Type\ContentTypeUpdateType
    ezrepoforms.field_definition.form_type.class: EzSystems\RepositoryForms\Form\Type\FieldDefinition\FieldDefinitionType

    ezrepoforms.field_type.form_mapper.ezstring.class: EzSystems\RepositoryForms\FieldType\Mapper\TextLineFormMapper

    ezrepoforms.validator.unique_content_type_identifier.class: EzSystems\RepositoryForms\Validator\Constraints\UniqueContentTypeIdentifierValidator
    ezrepoforms.validator.validator_configuration.class: EzSystems\RepositoryForms\Validator\Constraints\ValidatorConfigurationValidator
    ezrepoforms.validator.field_settings.class: EzSystems\RepositoryForms\Validator\Constraints\FieldSettingsValidator
    ezrepoforms.validator.default_field_value.class: EzSystems\RepositoryForms\Validator\Constraints\FieldDefinitionDefaultValueValidator

services:
    ezrepoforms.field_type_form_mapper.registry:
        class: %ezrepoforms.field_type_form_mapper.registry.class%

    ezrepoforms.content_type.update.form_type:
        class: %ezrepoforms.content_type.update.form_type.class%
        arguments: [@ezrepoforms.field_type_form_mapper.registry, @translator]
        tags:
            - {name: form.type, alias: ezrepoforms_contenttype_update}

    ezrepoforms.field_definition.form_type:
        class: %ezrepoforms.field_definition.form_type.class%
        arguments: [@ezrepoforms.field_type_form_mapper.registry, @ezpublish.api.service.field_type]
        tags:
            - { name: form.type, alias: ezrepoforms_fielddefinition_update }

    # FieldType form mappers
    ezrepoforms.field_type.form_mapper.ezstring:
        class: %ezrepoforms.field_type.form_mapper.ezstring.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezstring }

    # Validators
    ezrepoforms.validator.unique_content_type_identifier:
        class: %ezrepoforms.validator.unique_content_type_identifier.class%
        arguments: [@ezpublish.api.service.content_type]
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.unique_content_type_identifier }

    ezrepoforms.validator.field_type.abstract:
        class: EzSystems\RepositoryForms\Validator\Constraints\FieldTypeValidator
        arguments: [@ezpublish.api.service.field_type]
        abstract: true

    ezrepoforms.validator.validator_configuration:
        parent: ezrepoforms.validator.field_type.abstract
        class: %ezrepoforms.validator.validator_configuration.class%
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.validator_configuration }

    ezrepoforms.validator.field_settings:
        parent: ezrepoforms.validator.field_type.abstract
        class: %ezrepoforms.validator.field_settings.class%
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.field_settings }

    ezrepoforms.validator.default_field_value:
        parent: ezrepoforms.validator.field_type.abstract
        class: %ezrepoforms.validator.default_field_value.class%
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.default_field_value }
